// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.GameCharacterGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("race")]
        public Race Race { get; set; }

        [JsonProperty("class")]
        public Class Class { get; set; }

        [JsonProperty("background")]
        public string Background { get; set; }

        [JsonProperty("personality")]
        public string Personality { get; set; }

        [JsonProperty("motivation")]
        public string Motivation { get; set; }

        [JsonProperty("stats")]
        public Stats Stats { get; set; }

        [JsonProperty("hp")]
        public long Hp { get; set; }
    }

    public partial class Class
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("primaryStat")]
        public string PrimaryStat { get; set; }

        [JsonProperty("hitDie")]
        public string HitDie { get; set; }
    }

    public partial class Race
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("traits")]
        public string[] Traits { get; set; }
    }

    public partial class Stats
    {
        [JsonProperty("strength")]
        public Charisma Strength { get; set; }

        [JsonProperty("dexterity")]
        public Charisma Dexterity { get; set; }

        [JsonProperty("constitution")]
        public Charisma Constitution { get; set; }

        [JsonProperty("intelligence")]
        public Charisma Intelligence { get; set; }

        [JsonProperty("wisdom")]
        public Charisma Wisdom { get; set; }

        [JsonProperty("charisma")]
        public Charisma Charisma { get; set; }
    }

    public partial class Charisma
    {
        [JsonProperty("value")]
        public long Value { get; set; }

        [JsonProperty("modifier")]
        public long Modifier { get; set; }
    }
}
